<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="MayankHP" failures="2" tests="14" name="Test1" time="0.084" errors="0" timestamp="2022-05-07T20:13:27 EDT">
  <testcase classname="demo1.BeforeAfterExample" name="testC1M1" time="0.009"/>
  <testcase classname="demo1.BeforeAfterExample" name="testC1M2" time="0.002"/>
  <testcase classname="demo1.EnabledFalseExample" name="testC2M1" time="0.001"/>
  <testcase classname="demo1.EnabledFalseExample" name="testC2M2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [c2 method 2 working fine] but found [c2 method 2 working not fine]">
      <![CDATA[java.lang.AssertionError: expected [c2 method 2 working fine] but found [c2 method 2 working not fine]
at demo1.EnabledFalseExample.testC2M2(EnabledFalseExample.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testC2M2 -->
  <testcase classname="demo1.ExpectedExceptionExample" name="checkResult" time="0.001">
    <failure type="org.testng.TestException" message="
Method ExpectedExceptionExample.checkResult()[pri:0, instance:demo1.ExpectedExceptionExample@53142455] should have thrown an exception of type class java.lang.ArithmeticException">
      <![CDATA[org.testng.TestException: 
Method ExpectedExceptionExample.checkResult()[pri:0, instance:demo1.ExpectedExceptionExample@53142455] should have thrown an exception of type class java.lang.ArithmeticException
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkResult -->
  <testcase classname="demo1.ParameterExample" name="paramTest" time="0.001"/>
  <testcase classname="demo1.ParameterExample" name="testDataProvider" time="0.0"/>
  <testcase classname="demo1.ParameterExample" name="testDataProvider" time="0.001"/>
  <testcase classname="demo1.ParameterExample" name="testDataProvider" time="0.001"/>
  <testcase classname="demo1.ParameterExample" name="testDataProvider" time="0.001"/>
  <testcase classname="demo1.ParameterExample" name="testDataProvider" time="0.0"/>
  <testcase classname="demo1.InvocationCountExample" name="msgPrint" time="0.001"/>
  <testcase classname="demo1.InvocationCountExample" name="msgPrint" time="0.001"/>
  <testcase classname="demo1.SoftAssertExample" name="testSoftAssert" time="0.003"/>
  <testcase classname="demo1.EnabledFalseExample" name="testC2M3" time="0.0">
    <ignored/>
  </testcase> <!-- testC2M3 -->
</testsuite> <!-- Test1 -->
